[2024-10-13T10:57:44.647+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-13T10:57:44.654+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2024-10-13T10:56:39.533856+00:00 [queued]>
[2024-10-13T10:57:44.657+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2024-10-13T10:56:39.533856+00:00 [queued]>
[2024-10-13T10:57:44.657+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-13T10:57:44.661+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): get_data> on 2024-10-13 10:56:39.533856+00:00
[2024-10-13T10:57:44.663+0000] {standard_task_runner.py:72} INFO - Started process 57925 to run task
[2024-10-13T10:57:44.664+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'manual__2024-10-13T10:56:39.533856+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmphw2swfn3']
[2024-10-13T10:57:44.664+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask get_data
[2024-10-13T10:57:44.691+0000] {task_command.py:467} INFO - Running <TaskInstance: youtube_comments_score.get_data manual__2024-10-13T10:56:39.533856+00:00 [running]> on host haserver
[2024-10-13T10:57:44.723+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T10:56:39.533856+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-13T10:56:39.533856+00:00'
[2024-10-13T10:57:44.723+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-13T10:57:44.729+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-13T10:57:44.729+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/dblab/haeun/mlops/ml_***/ex1/scripts/get_data.py']
[2024-10-13T10:57:44.732+0000] {subprocess.py:86} INFO - Output:
[2024-10-13T10:57:48.349+0000] {subprocess.py:93} INFO - 2024/10/13 10:57:48 INFO mlflow.tracking._tracking_service.client: üèÉ View run crawling-eel-14 at: http://localhost:8088/#/experiments/862399464515859752/runs/023ab38ca82444659c42d12ff2241b59.
[2024-10-13T10:57:48.349+0000] {subprocess.py:93} INFO - 2024/10/13 10:57:48 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://localhost:8088/#/experiments/862399464515859752.
[2024-10-13T10:57:48.356+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-10-13T10:57:48.356+0000] {subprocess.py:93} INFO -   File "/home/dblab/haeun/mlops/ml_***/ex1/scripts/get_data.py", line 40, in <module>
[2024-10-13T10:57:48.356+0000] {subprocess.py:93} INFO -     with open(f'{PROJECT_PATH}/datasets/data.csv', 'a') as f:
[2024-10-13T10:57:48.357+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-13T10:57:48.357+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/home/dblab/haeun/mlops/ml_***/ex1/datasets/data.csv'
[2024-10-13T10:57:48.428+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-13T10:57:48.436+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-13T10:57:48.438+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=youtube_comments_score, task_id=get_data, run_id=manual__2024-10-13T10:56:39.533856+00:00, execution_date=20241013T105639, start_date=20241013T105744, end_date=20241013T105748
[2024-10-13T10:57:48.443+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-13T10:57:48.444+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 57925)
Traceback (most recent call last):
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-13T10:57:48.454+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-13T10:57:48.491+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-13T10:57:48.494+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
