[2024-10-13T11:42:33.130+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-13T11:42:33.138+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2024-10-13T11:42:32.710288+00:00 [queued]>
[2024-10-13T11:42:33.140+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2024-10-13T11:42:32.710288+00:00 [queued]>
[2024-10-13T11:42:33.141+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-13T11:42:33.146+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): get_data> on 2024-10-13 11:42:32.710288+00:00
[2024-10-13T11:42:33.148+0000] {standard_task_runner.py:72} INFO - Started process 65155 to run task
[2024-10-13T11:42:33.149+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'manual__2024-10-13T11:42:32.710288+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmp_p3b10v2']
[2024-10-13T11:42:33.149+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask get_data
[2024-10-13T11:42:33.185+0000] {task_command.py:467} INFO - Running <TaskInstance: youtube_comments_score.get_data manual__2024-10-13T11:42:32.710288+00:00 [running]> on host haserver
[2024-10-13T11:42:33.219+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T11:42:32.710288+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-13T11:42:32.710288+00:00'
[2024-10-13T11:42:33.220+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-13T11:42:33.225+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-13T11:42:33.225+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/dblab/haeun/mlops/ml_***/ex1/scripts/get_data.py']
[2024-10-13T11:42:33.228+0000] {subprocess.py:86} INFO - Output:
[2024-10-13T11:42:36.083+0000] {subprocess.py:93} INFO - 2024/10/13 11:42:36 INFO mlflow.tracking._tracking_service.client: üèÉ View run bald-stoat-830 at: http://localhost:8088/#/experiments/862399464515859752/runs/7aeb4a769f4b41e4b90a3b9a7cbe4122.
[2024-10-13T11:42:36.084+0000] {subprocess.py:93} INFO - 2024/10/13 11:42:36 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://localhost:8088/#/experiments/862399464515859752.
[2024-10-13T11:42:36.090+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-10-13T11:42:36.091+0000] {subprocess.py:93} INFO -   File "/home/dblab/haeun/mlops/ml_***/ex1/scripts/get_data.py", line 35, in <module>
[2024-10-13T11:42:36.091+0000] {subprocess.py:93} INFO -     for item in data['items']:
[2024-10-13T11:42:36.092+0000] {subprocess.py:93} INFO -                 ~~~~^^^^^^^^^
[2024-10-13T11:42:36.092+0000] {subprocess.py:93} INFO - KeyError: 'items'
[2024-10-13T11:42:36.168+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-13T11:42:36.176+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-13T11:42:36.179+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=get_data, run_id=manual__2024-10-13T11:42:32.710288+00:00, execution_date=20241013T114232, start_date=20241013T114233, end_date=20241013T114236
[2024-10-13T11:42:36.186+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-13T11:42:36.187+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 36 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 65155)
Traceback (most recent call last):
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-13T11:42:36.212+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-13T11:42:36.252+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-13T11:42:36.255+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
